import type { FontCategory } from "./types";

export const FONT_CATEGORY_KR: Record<FontCategory, string> = {
  CUTE: "귀여운",
  RETRO: "레트로",
  EMOTIONAL: "감성적인",
  UNIQUE: "개성있는",
  RIGID: "딱딱한",
  SERIOUS: "진지한",
  ELEGANT: "우아한",
  MODERN: "모던한",
  LYRICAL: "서정적인",
  SCARY: "무서운",
  LIGHT: "경쾌한",
};

export type FontCategory_Map =
  | 'CUTE'
  | 'RETRO'
  | 'EMOTIONAL'
  | 'UNIQUE'
  | 'RIGID'
  | 'SERIOUS'
  | 'ELEGANT'

export const FONT_CATEGORY_MAP: Record<FontCategory_Map, string> = {
  CUTE: "귀여운",
  RETRO: "레트로",
  EMOTIONAL: "감성적인",
  UNIQUE: "개성있는",
  RIGID: "딱딱한",
  SERIOUS: "진지한",
  ELEGANT: "우아한",
};

export const FONTS_BY_CATEGORY = {
  CUTE: [1, 6, 13, 14, 18, 22, 26, 28, 29, 39, 41, 42, 43, 56, 58, 59, 62, 65],
  RETRO: [8, 9, 10, 19, 23, 46],
  EMOTIONAL: [20, 21, 24, 25, 27, 34, 36, 40, 48, 50, 51, 55, 60, 63, 68],
  UNIQUE: [4, 30, 35, 37, 38, 44, 47, 54, 57],
  RIGID: [31, 53, 64, 67, 69],
  SERIOUS: [32, 33, 45, 49, 61],
  ELEGANT:[3, 7, 52, 66],
  MODERN:[2],
  LYRICAL:[5, 15],
  SCARY:[11, 12],
  LIGHT:[16, 17],
};

export interface FontAsset {
  label?: string;
  fontFamily?: string;
  url: string | null;
}

// export const FONT_MAP: Record<number, { label: string; fontFamily: string; url: string | null }> = {
//   1: { label: 'Sandoll 거복', fontFamily: "var(--font-1)", url: null },
//   2: { label: 'Sandoll 고딕NeoCond', fontFamily: "var(--font-2)", url: null },
//   3: { label: 'SD 잔', fontFamily: "var(--font-3)", url: null },
//   4: { label: 'SD 워키토키Round', fontFamily: "var(--font-4)", url: null },
//   5: { label: 'SD 프시케', fontFamily: "var(--font-5)", url: null },
//   6: { label: 'SD 흐루링', fontFamily: "var(--font-6)", url: null },
//   7: { label: 'SD 피쉬테일', fontFamily: "var(--font-7)", url: null },
//   8: { label: 'SD 픽셀비밀쪽지', fontFamily: "var(--font-8)", url: null },
//   9: { label: 'SD 픽셀굿밤', fontFamily: "var(--font-9)", url: null },
//   10: { label: 'SD 픽셀요술지팡이', fontFamily: "var(--font-10)", url: null },
//   11: { label: 'Sandoll 으스스', fontFamily: "var(--font-11)", url: null },
//   12: { label: 'Sandoll 끼기긱', fontFamily: "var(--font-12)", url: null },
//   13: { label: 'Sandoll 호요요Color', fontFamily: "var(--font-13)", url: null },
//   14: { label: 'Sandoll 둥굴림2', fontFamily: "var(--font-14)", url: null },
//   15: { label: 'Sandoll 에필로그', fontFamily: "var(--font-15)", url: null },
//   16: { label: 'Sandoll 슛돌이', fontFamily: "var(--font-16)", url: null },
//   17: { label: 'Sandoll 빼빼로데이', fontFamily: "var(--font-17)", url: null },
//   18: { label: '학교안심 이어달리기', fontFamily: 'SchoolSafetyRelay', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/2510-1@1.0/HakgyoansimYieodalligiL.woff2' },
//   19: { label: '갈무리9', fontFamily: 'Galmuri9', url: 'https://cdn.jsdelivr.net/npm/galmuri@latest/dist/galmuri.css' },
//   20: { label: 'kcc손기정체', fontFamily: 'KccSonGigeong', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2212@1.0/KCC-Sonkeechung.woff2' },
//   21: { label: '윤초록우산어린이민국', fontFamily: 'YunChorokwoosanEoriniMinguk', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/2408@1.0/YoonChildfundkoreaMinGuk.woff2' },
//   22: { label: '온글잎콘콘체', fontFamily: 'OngleipKonkon', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/2412-1@1.0/Ownglyph_corncorn-Rg.woff2' },
//   23: { label: 'Neo둥근모', fontFamily: 'NeoDonggeunmo', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2001@1.3/NeoDunggeunmo.woff' },
//   24: { label: '온글잎안될과학궤도', fontFamily: 'AndolScienceOrbit', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2205@1.0/Unreal_science_orbit.woff2' },
//   25: { label: '유설체', fontFamily: 'Yuseol', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/2508-2@1.0/YooSeol.woff2' },
//   26: { label: '온글잎 박다현체', fontFamily: 'OngleipParkDahyeon', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/2411-3@1.0/Ownglyph_ParkDaHyun.woff2' },
//   27: { label: '그리운 사막의 연우체', fontFamily: 'NostalgicDesertYeonwoo', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/2508-2@1.0/Griun_YEONWOO-Rg.woff2' },
//   28: { label: '제주돌담체', fontFamily: 'JejuStoneWall', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2210-EF@1.0/EF_jejudoldam.woff2' },
//   29: { label: '학교안심 시간표', fontFamily: 'SchoolSafetySchedule', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/2508-2@1.0/HakgyoansimSiganpyoR.woff2' },
//   30: { label: '평창평화체', fontFamily: 'PyeongchangPeace', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2206-02@1.0/PyeongChangPeace-Light.woff2' },
//   31: { label: 'ACC어린이 가을담은체', fontFamily: 'AccChildrenSFall', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2112-2@1.0/ACCchildrensky.woff' },
//   32: { label: '조선궁서체', fontFamily: 'JoseonPalace', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-04@1.0/ChosunGs.woff' },
//   33: { label: '신라 문화체', fontFamily: 'Shilla', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2206-02@1.0/Shilla_CultureM-Medium.woff2' },
//   34: { label: '더페이스샵 잉크립퀴드체', fontFamily: 'InkLiquid', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_one@1.0/InkLipquid.woff' },
//   35: { label: '세종자으미모으미', fontFamily: 'SejongJaeumiMoeumiBold', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/2510-3@1.0/SejongJaeumiMoeumi-Bold.woff2' },
//   36: { label: '인천교육자람체', fontFamily: 'IncheonEducation', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2307-2@1.0/iceJaram-Rg.woff2' },
//   37: { label: '산돌삼립호빵체Outline', fontFamily: 'SandollSamlipHobbangOutline', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts-20-12@1.0/SDSamliphopangche_Outline.woff' },
//   38: { label: '피플퍼스트투쟁', fontFamily: 'PeopleFirstStruggle', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/2406-2@1.0/PeoplefirstFightingTTF.woff2' },
//   39: { label: '온글잎 의연체', fontFamily: 'OngleipEoyeonce', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2105@1.1/Uiyeun.woff' },
//   40: { label: '신동엽 손글씨', fontFamily: 'ShinDongYeopHandwriting', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_231029@1.1/ShinDongYupHandwriting-R.woff2' },
//   41: { label: '낭만있구미체', fontFamily: 'RomanticGumi', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/2410-1@1.0/GumiRomanceTTF.woff2' },
//   42: { label: '넥슨메이플스토리', fontFamily: 'NexonMaplestory', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-04@2.1/MaplestoryOTFLight.woff' },
//   43: { label: '전화선체', fontFamily: 'PhoneLine', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2202-2@1.0/JeonHwaseon.woff' },
//   44: { label: '집토끼체', fontFamily: 'HsJibtokiRound', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2302@1.0/HSJiptokki-Round.woff2' },
//   45: { label: '한글재민체', fontFamily: 'HangulJaemin', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-10-21@1.0/Jaemin.woff' },
//   46: { label: '도스필기', fontFamily: 'DosHandwriting', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2304-2@1.0/DOSPilgiMedium.woff2' },
//   47: { label: '삼립크리미 화이트', fontFamily: 'SamlipCreamyWhite', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/2408-4@1.0/TTSamlipCreamyWhiteR.woff2' },
//   48: { label: 'KCC 안창호체', fontFamily: 'KccAnchangho', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2402_1@1.0/KCC-Ahnchangho.woff2' },
//   49: { label: '이순신', fontFamily: 'LeeSunShin', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_two@1.0/YiSunShinRegular.woff' },
//   50: { label: '카페24빛나는별', fontFamily: 'Cafe24ShiningStar', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_twelve@1.1/Cafe24Shiningstar.woff' },
//   51: { label: 'tvn즐거운이야기', fontFamily: 'JoyfulStory', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_two@1.0/OTEnjoystoriesBA.woff' },
//   52: { label: 'OG르네상스비밀', fontFamily: 'OgRenaissanceSecret', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2312-1@1.1/OG_Renaissance_Secret-Rg.woff2' },
//   53: { label: '배달의민족 한나체', fontFamily: 'HannaPro', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_seven@1.0/BMHANNAPro.woff' },
//   54: { label: 'HS산토끼체2.0', fontFamily: 'HsSantoki20', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/2405@1.0/HSSanTokki20-Regular.woff2' },
//   55: { label: 'ylee추억은잠들지않는다', fontFamily: 'YleeMemoriesNeverSleep', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2205@1.0/yleeMortalHeartImmortalMemory.woff2' },
//   56: { label: '그리운 규원체', fontFamily: 'MissedGyuwon', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/2510-1@1.0/Griun_Gyuwon-Rg.woff2' },
//   57: { label: '콜디웹툰메이커온글잎폰트', fontFamily: 'KoldiWebtoonMakerOngleifFont', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/2508-2@1.0/Ownglyph_Coldywebtoonmaker-Rg.woff2' },
//   58: { label: '마포배낭여행', fontFamily: 'MapoBackpackTravel', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2001@1.1/MapoBackpackingA.woff' },
//   59: { label: '꽃소금체', fontFamily: 'Kkotsogum', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2210-2@1.0/FlowerSalt.woff2' },
//   60: { label: '상주다정다감체', fontFamily: 'SangjuDajeongdagam', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2112@1.0/SANGJUDajungdagam.woff' },
//   61: { label: '한컴훈민정음가로쓰기', fontFamily: 'HancomHunminjeongeum', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/2406-1@1.0/HancomHoonminjeongeumH.woff' },
//   62: { label: '온글잎류류체', fontFamily: 'OngleipRyuryu', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/2405-2@1.0/Ownglyph_ryurue-Rg.woff2' },
//   63: { label: '학교안심바른바탕', fontFamily: 'SchoolSafetyFoundation', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2307-2@1.0/HakgyoansimBareonbatangR.woff2' },
//   64: { label: '창원단감아삭체', fontFamily: 'ChangwonDanggamAsak', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2108@1.1/CWDangamAsac-Bold.woff' },
//   65: { label: '다래손글씨', fontFamily: 'DaraeHandwriting', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_three@1.0/drfont_daraehand.woff' },
//   66: { label: 'HS봄바람체 2.0', fontFamily: 'HsBombaram20', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_one@1.0/HSBombaram.woff' },
//   67: { label: '프리텐다드', fontFamily: 'Pretendard', url: null },
//   68: { label: '나눔명조', fontFamily: 'NanumMyeongjo', url: 'https://fonts.gstatic.com/s/nanummyeongjo/v31/9Btx3DZF0dXLMZlywRbVRNhxy1LueHI8j7a277xGHHfvDTP5cQDfPh1ShL-7.0.woff2' },
//   69: { label: '나눔스퀘어네오', fontFamily: 'NanumSquareNeo', url: null },
// };

export const FONT_MAP: Record<number, { label: string; fontFamily: string; url: string | null }> = {
  1: { label: '산돌삼립호빵체Outline', fontFamily: 'SandollSamlipHobbangOutline', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts-20-12@1.0/SDSamliphopangche_Outline.woff' },
  2: { label: '나눔스퀘어네오', fontFamily: 'NanumSquareNeo', url: 'https://hangeul.pstatic.net/hangeul_static/webfont/NanumSquareNeo/NanumSquareNeoTTF-aLt.woff2' },
  3: { label: '배달의민족 한나체', fontFamily: 'HannaPro', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_seven@1.0/BMHANNAPro.woff' },
  4: { label: '학교안심 이어달리기', fontFamily: 'SchoolSafetyRelay', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/2510-1@1.0/HakgyoansimYieodalligiL.woff2' },
  5: { label: '갈무리9', fontFamily: 'Galmuri9', url: 'https://cdn.jsdelivr.net/npm/galmuri@latest/dist/galmuri.css' },
  6: { label: 'kcc손기정체', fontFamily: 'KccSonGigeong', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2212@1.0/KCC-Sonkeechung.woff2' },
  7: { label: '윤초록우산어린이민국', fontFamily: 'YunChorokwoosanEoriniMinguk', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/2408@1.0/YoonChildfundkoreaMinGuk.woff2' },
  8: { label: '온글잎콘콘체', fontFamily: 'OngleipKonkon', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/2412-1@1.0/Ownglyph_corncorn-Rg.woff2' },
  9: { label: 'Neo둥근모', fontFamily: 'NeoDonggeunmo', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2001@1.3/NeoDunggeunmo.woff' },
  10: { label: '온글잎안될과학궤도', fontFamily: 'AndolScienceOrbit', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2205@1.0/Unreal_science_orbit.woff2' },
  11: { label: '유설체', fontFamily: 'Yuseol', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/2508-2@1.0/YooSeol.woff2' },
  12: { label: '온글잎 박다현체', fontFamily: 'OngleipParkDahyeon', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/2411-3@1.0/Ownglyph_ParkDaHyun.woff2' },
  13: { label: '그리운 사막의 연우체', fontFamily: 'NostalgicDesertYeonwoo', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/2508-2@1.0/Griun_YEONWOO-Rg.woff2' },
  14: { label: '제주돌담체', fontFamily: 'JejuStoneWall', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2210-EF@1.0/EF_jejudoldam.woff2' },
  15: { label: '학교안심 시간표', fontFamily: 'SchoolSafetySchedule', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/2508-2@1.0/HakgyoansimSiganpyoR.woff2' },
  16: { label: '평창평화체', fontFamily: 'PyeongchangPeace', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2206-02@1.0/PyeongChangPeace-Light.woff2' },
  17: { label: 'ACC어린이 가을담은체', fontFamily: 'AccChildrenSFall', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2112-2@1.0/ACCchildrensky.woff' },
  18: { label: '조선궁서체', fontFamily: 'JoseonPalace', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-04@1.0/ChosunGs.woff' },
  19: { label: '신라 문화체', fontFamily: 'Shilla', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2206-02@1.0/Shilla_CultureM-Medium.woff2' },
  20: { label: '더페이스샵 잉크립퀴드체', fontFamily: 'InkLiquid', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_one@1.0/InkLipquid.woff' },
  21: { label: '세종자으미모으미', fontFamily: 'SejongJaeumiMoeumiBold', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/2510-3@1.0/SejongJaeumiMoeumi-Bold.woff2' },
  22: { label: '인천교육자람체', fontFamily: 'IncheonEducation', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2307-2@1.0/iceJaram-Rg.woff2' },
  23: { label: '피플퍼스트투쟁', fontFamily: 'PeopleFirstStruggle', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/2406-2@1.0/PeoplefirstFightingTTF.woff2' },
  24: { label: '온글잎 의연체', fontFamily: 'OngleipEoyeonce', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2105@1.1/Uiyeun.woff' },
  25: { label: '신동엽 손글씨', fontFamily: 'ShinDongYeopHandwriting', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_231029@1.1/ShinDongYupHandwriting-R.woff2' },
  26: { label: '낭만있구미체', fontFamily: 'RomanticGumi', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/2410-1@1.0/GumiRomanceTTF.woff2' },
  27: { label: '넥슨메이플스토리', fontFamily: 'NexonMaplestory', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-04@2.1/MaplestoryOTFLight.woff' },
  28: { label: '전화선체', fontFamily: 'PhoneLine', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2202-2@1.0/JeonHwaseon.woff' },
  29: { label: '집토끼체', fontFamily: 'HsJibtokiRound', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2302@1.0/HSJiptokki-Round.woff2' },
  30: { label: '한글재민체', fontFamily: 'HangulJaemin', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-10-21@1.0/Jaemin.woff' },
  31: { label: '도스필기', fontFamily: 'DosHandwriting', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2304-2@1.0/DOSPilgiMedium.woff2' },
  32: { label: '삼립크리미 화이트', fontFamily: 'SamlipCreamyWhite', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/2408-4@1.0/TTSamlipCreamyWhiteR.woff2' },
  33: { label: 'KCC 안창호체', fontFamily: 'KccAnchangho', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2402_1@1.0/KCC-Ahnchangho.woff2' },
  34: { label: '이순신', fontFamily: 'LeeSunShin', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_two@1.0/YiSunShinRegular.woff' },
  35: { label: '카페24빛나는별', fontFamily: 'Cafe24ShiningStar', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_twelve@1.1/Cafe24Shiningstar.woff' },
  36: { label: 'tvn즐거운이야기', fontFamily: 'JoyfulStory', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_two@1.0/OTEnjoystoriesBA.woff' },
  37: { label: 'OG르네상스비밀', fontFamily: 'OgRenaissanceSecret', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2312-1@1.1/OG_Renaissance_Secret-Rg.woff2' },
  38: { label: 'HS산토끼체2.0', fontFamily: 'HsSantoki20', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/2405@1.0/HSSanTokki20-Regular.woff2' },
  39: { label: 'ylee추억은잠들지않는다', fontFamily: 'YleeMemoriesNeverSleep', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2205@1.0/yleeMortalHeartImmortalMemory.woff2' },
  40: { label: '그리운 규원체', fontFamily: 'MissedGyuwon', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/2510-1@1.0/Griun_Gyuwon-Rg.woff2' },
  41: { label: '콜디웹툰메이커온글잎폰트', fontFamily: 'KoldiWebtoonMakerOngleifFont', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/2508-2@1.0/Ownglyph_Coldywebtoonmaker-Rg.woff2' },
  42: { label: '마포배낭여행', fontFamily: 'MapoBackpackTravel', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2001@1.1/MapoBackpackingA.woff' },
  43: { label: '꽃소금체', fontFamily: 'Kkotsogum', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2210-2@1.0/FlowerSalt.woff2' },
  44: { label: '상주다정다감체', fontFamily: 'SangjuDajeongdagam', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2112@1.0/SANGJUDajungdagam.woff' },
  45: { label: '한컴훈민정음가로쓰기', fontFamily: 'HancomHunminjeongeum', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/2406-1@1.0/HancomHoonminjeongeumH.woff' },
  46: { label: '온글잎류류체', fontFamily: 'OngleipRyuryu', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/2405-2@1.0/Ownglyph_ryurue-Rg.woff2' },
  47: { label: '학교안심바른바탕', fontFamily: 'SchoolSafetyFoundation', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2307-2@1.0/HakgyoansimBareonbatangR.woff2' },
  48: { label: '창원단감아삭체', fontFamily: 'ChangwonDanggamAsak', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2108@1.1/CWDangamAsac-Bold.woff' },
  49: { label: '다래손글씨', fontFamily: 'DaraeHandwriting', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_three@1.0/drfont_daraehand.woff' },
  50: { label: 'HS봄바람체 2.0', fontFamily: 'HsBombaram20', url: 'https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_one@1.0/HSBombaram.woff' },
  51: { label: '프리텐다드', fontFamily: 'Pretendard', url: null },
  52: { label: '나눔명조', fontFamily: 'NanumMyeongjo', url: 'https://fonts.gstatic.com/s/nanummyeongjo/v31/9Btx3DZF0dXLMZlywRbVRNhxy1LueHI8j7a277xGHHfvDTP5cQDfPh1ShL-7.0.woff2' },
};
